import { readFile } from "node:fs/promises";
import { join } from "node:path";
import {
  postprocessChapterAnima,
  postprocessChapterTrophy,
  postprocessChapterZone,
  postprocessChromaGridSheet,
  sha256Hex,
} from "./assets.mjs";
import { BOSS_SEEKER_POSES } from "./constants.mjs";
import { writeChapterOutputs } from "./io.mjs";
import {
  applySlotToBundle,
  loadOrCreateAssetBundle,
  rebuildFromAssets,
} from "./manifest.mjs";
import {
  assetMode,
  isProductionAssetSource,
  readAssetSources,
  withManualAssetSource,
  writeAssetSources,
} from "./provenance.mjs";
import { validateChapterDraft, validateDesign } from "./validate.mjs";

const PNG_SIGNATURE = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);

export function parseManualGenerationNotes(text) {
  const field = (name) =>
    text.match(new RegExp(`^- ${name}:\\s*(.+)$`, "mi"))?.[1]?.trim() ?? "";
  const provider = field("Provider");
  const operator = field("Generated by");
  const generatedAt = field("Generated at");
  if (!/chatgpt/i.test(provider)) throw new Error("MANUAL_NOTES_PROVIDER_INVALID");
  if (operator.length < 2 || operator.includes("<")) {
    throw new Error("MANUAL_NOTES_OPERATOR_INVALID");
  }
  if (generatedAt.length < 4 || generatedAt.includes("<")) {
    throw new Error("MANUAL_NOTES_DATE_INVALID");
  }
  return { provider, operator, generatedAt };
}

export function manualInputRelativePaths(slot, ctx) {
  if (slot.startsWith("anima:")) {
    return [`manual_inbox/animas/${slot.slice("anima:".length)}.png`];
  }
  if (slot.startsWith("zone:")) {
    const filename = `zone-${Number(slot.slice("zone:".length))}.png`;
    return [
      `manual_inbox/zones/${filename}`,
      // ponytail: compatibility untuk handoff Sugarworks awal; hapus setelah inbox dipindah.
      `manual_inbox/animas/${filename}`,
    ];
  }
  if (slot === "boss_seeker") {
    return [`manual_inbox/boss/${ctx.bossLocalFilename()}`];
  }
  if (slot === "trophy") {
    return [`manual_inbox/trophy/${ctx.trophyLocalFilename()}`];
  }
  throw new Error(`MANUAL_SLOT_INVALID:${slot}`);
}

function manualSlotSet(input, ctx) {
  if (!input) return null;
  const allowed = new Set(ctx.imageSlots());
  const selected = new Set(
    String(input).split(",").map((part) => part.trim()).filter(Boolean),
  );
  for (const slot of selected) {
    if (!allowed.has(slot)) throw new Error(`MANUAL_SLOT_INVALID:${slot}`);
  }
  return selected;
}

async function readManualInput(chapterDir, slot, ctx) {
  const found = [];
  for (const relativePath of manualInputRelativePaths(slot, ctx)) {
    try {
      found.push({
        relativePath,
        bytes: await readFile(join(chapterDir, ...relativePath.split("/"))),
      });
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }
  }
  if (found.length > 1) throw new Error(`MANUAL_INPUT_AMBIGUOUS:${slot}`);
  return found[0] ?? null;
}

function assertPng(bytes, slot) {
  if (bytes.length < PNG_SIGNATURE.length ||
      !Buffer.from(bytes.subarray(0, PNG_SIGNATURE.length)).equals(PNG_SIGNATURE)) {
    throw new Error(`MANUAL_INPUT_NOT_PNG:${slot}`);
  }
}

async function postprocessManualSlot(slot, raw, ctx, {
  cleanupIdleSeamLeaks = false,
} = {}) {
  if (slot.startsWith("anima:")) {
    return postprocessChapterAnima(
      raw,
      ctx.getCastMember(slot.slice("anima:".length)),
      { cleanupIdleSeamLeaks },
    );
  }
  if (slot.startsWith("zone:")) return postprocessChapterZone(raw);
  if (slot === "boss_seeker") {
    return postprocessChromaGridSheet(raw, {
      poses: BOSS_SEEKER_POSES,
      meta: { seeker_id: ctx.design.boss_seeker.id },
    });
  }
  if (slot === "trophy") return postprocessChapterTrophy(raw);
  throw new Error(`MANUAL_SLOT_INVALID:${slot}`);
}

export async function runManualIngest({
  chapterDir,
  ctx,
  slots = null,
  cleanupSeams = null,
  apply = false,
}) {
  validateDesign(ctx.design, ctx.brief, ctx);
  let sources = await readAssetSources(chapterDir);
  const requested = manualSlotSet(slots, ctx);
  const cleanupRequested = manualSlotSet(cleanupSeams, ctx) ?? new Set();
  for (const slot of cleanupRequested) {
    if (!slot.startsWith("anima:")) throw new Error(`MANUAL_SEAM_CLEANUP_INVALID:${slot}`);
    if (requested && !requested.has(slot)) {
      throw new Error(`MANUAL_SEAM_CLEANUP_NOT_SELECTED:${slot}`);
    }
  }
  const inputs = [];
  const failed = [];
  const skipped = [];

  for (const slot of ctx.imageSlots()) {
    if (requested && !requested.has(slot)) continue;
    try {
      const input = await readManualInput(chapterDir, slot, ctx);
      if (input) {
        inputs.push({ slot, ...input });
      } else if (requested || !isProductionAssetSource(sources.slots?.[slot]?.source)) {
        failed.push({ slot, error: "MANUAL_INPUT_MISSING" });
      } else {
        skipped.push({ slot, reason: "existing_production_source" });
      }
    } catch (error) {
      failed.push({
        slot,
        error: String(error instanceof Error ? error.message : error).slice(0, 300),
      });
    }
  }

  const prepared = [];

  for (const input of inputs) {
    try {
      assertPng(input.bytes, input.slot);
      const existingCleanup =
        sources.slots?.[input.slot]?.postprocess?.mode ===
        "remove_detached_idle_components_v1";
      const asset = await postprocessManualSlot(input.slot, input.bytes, ctx, {
        cleanupIdleSeamLeaks: cleanupRequested.has(input.slot) || existingCleanup,
      });
      prepared.push({
        ...input,
        asset,
        inputHash: sha256Hex(input.bytes),
      });
    } catch (error) {
      failed.push({
        slot: input.slot,
        error: String(error instanceof Error ? error.message : error).slice(0, 300),
      });
    }
  }

  let metadata = null;
  let notesHash = null;
  if (inputs.length > 0) {
    try {
      const notes = await readFile(
        join(chapterDir, "manual_inbox", "generation-notes.md"),
        "utf8",
      );
      metadata = parseManualGenerationNotes(notes);
      notesHash = sha256Hex(Buffer.from(notes));
    } catch (error) {
      failed.push({
        slot: "generation-notes",
        error: String(error instanceof Error ? error.message : error).slice(0, 300),
      });
    }
  }

  const passed = prepared.map((entry) => ({
    slot: entry.slot,
    input_path: entry.relativePath,
    input_sha256: entry.inputHash,
    output_sha256: entry.asset.hash,
  }));
  if (failed.length > 0) {
    return {
      ok: false,
      mode: apply ? "apply" : "preview",
      passed,
      failed,
      skipped,
      written: false,
    };
  }
  if (prepared.length === 0) {
    return {
      ok: true,
      mode: apply ? "apply" : "preview",
      passed: [],
      failed: [],
      skipped,
      written: false,
    };
  }
  if (!apply) {
    return { ok: true, mode: "preview", passed, failed: [], skipped, written: false };
  }

  const bundle = await loadOrCreateAssetBundle(chapterDir, ctx);
  for (const entry of prepared) {
    applySlotToBundle(bundle, entry.slot, entry.asset);
    sources = withManualAssetSource(sources, entry.slot, {
      provider: metadata.provider,
      operator: metadata.operator,
      generatedAt: metadata.generatedAt,
      inputPath: entry.relativePath,
      inputHash: entry.inputHash,
      outputHash: entry.asset.hash,
      notesHash,
      postprocess: entry.asset.manifest?.qa?.seam_cleanup ?? null,
    });
  }
  const rebuilt = await rebuildFromAssets(chapterDir, bundle, ctx, assetMode(ctx, sources));
  validateChapterDraft(rebuilt.manifest, ctx);
  const approval = await writeChapterOutputs(chapterDir, rebuilt, ctx);
  await writeAssetSources(chapterDir, sources);
  return {
    ok: true,
    mode: "apply",
    passed,
    failed: [],
    skipped,
    written: true,
    asset_mode: rebuilt.manifest.factory.mode,
    manifest_hash: rebuilt.manifest.manifest_hash,
    approval,
  };
}
